baseURL = "http://iniciativas19.labcd.mx/"
languageCode = "mx-es"
title = " Iniciativas 19"
theme = "hyde"
subtitle = "Ciudad Creativa y resiliente"

[[menu.main]]
    name = "Fondo"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
    identifier = "about"
    url = "/fondo/"

[[menu.main]]
    name = "Iniciativas"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
    identifier = "Iniciativas"
    url = "/iniciativas/"


[params]
  themeColor = "theme-base-09"
  description = "Ciudad Creativa y Resiliente"
  author = "Edgar Robles"
  [taxonomies]
    tag = "tags"
    category = "categories"
