baseURL = "http://iniciativas19.labcd.mx/"
languageCode = "mx-es"
title = " Iniciativas 19"
theme = "hyde"
subtitle = "Ciudad Creativa y resiliente"

[[menu.main]]
    name = "Inicio"
    weight = -180
    identifier = "inicio"
    url = "/"

# [[menu.main]]
#     name = "Fondo"
#     weight = -110
#     identifier = "about"
#     url = "/fondo/"
#
[[menu.main]]
    name = "Historias"
    weight = -110
    identifier = "historias"
    url = "/historias/"
# #

[[menu.main]]
    name = "Iniciativas "
    weight = -140
    identifier = "Iniciativas 19"
    url = "/iniciativas/"
    # pre = "<i class='fa fa-heart'></i>"

# [[menu.main]]
#     name = "Co-work"
#     weight = 100
#     identifier = "Co-work"
#     url = "/co-work/"

[params]
  themeColor = "theme-base-09"
  description = "Ciudad Creativa y Resiliente"
  author = "Edgar Robles"
  [taxonomies]
    tag = "tags"
    category = "categories"
